name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Build C# Code
      run: dotnet build

    - name: Test C# Code
      run: dotnet test

    - name: Build TypeScript Code
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build

    - name: Run TypeScript Linter
      working-directory: ./DotnetTemplate.Web
      run: npm run lint

    - name: Run TypeScript Tests
      working-directory: ./DotnetTemplate.Web
      run: npm t

    - name: Slack Notification
    id: slack
    uses: slackapi/slack-github-action@v1.26.0
    with:
      # This data can be any valid JSON from a previous step in the GitHub Action
      payload: |
        "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
          }
        ]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      